# Generated by Django 4.0.4 on 2022-05-25 19:48

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='data',
        ),
        migrations.AddField(
            model_name='image',
            name='pathImage',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=recipes.models.TextFieldImpl(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=recipes.models.TextFieldImpl(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
