# Generated by Django 4.0.4 on 2022-05-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_category_alias_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='recipe',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.recipe'),
        ),
    ]
