# Generated by Django 4.0.4 on 2022-05-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_comment_user_alter_recipe_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='recipe',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe'),
        ),
    ]
