# Generated by Django 4.0.4 on 2022-05-28 18:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_category_recipe_alter_comment_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
